services:
  app:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: php-app
    volumes:
      - .:/var/www/html   # Monta todo el proyecto
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network
  node:
    image: node:24
    container_name: tailwind-node
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:

networks:
  app-network:
